baseURL: 'https://jpldcarvalho.com/'
theme: "anubis"
languageCode: 'en-us'
title: "Hi, I'm Carvalho"

params:
  author: "jpldcarvalho"
  email: me@jpldcarvalho.com
  avatar: "https://avatars.githubusercontent.com/u/5263301"
  style: dark-without-switcher
  social:
  - id: github
    name: jpldcarvalho
  - id: twitter
    name: jpldcarvalho
  - id: linkedin
    name: jpldcarvalho