name: Build and deploy
on: push
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.13
      - run: npm install
      - run: npm run build
  deploy:
    uses: peaceiris/actions-gh-pages@v3
    if: github.ref == 'refs/head/master'
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./public
